src/Entity/QrCode.php
<?php

namespace App\Entity;

abstract class QrCode
{
    abstract public function getId(): ?int;
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <link rel="apple-touch-icon" sizes="76x76" href="{{ asset('img/apple-icon.png') }}">
        <link rel="icon" type="image/png" href="{{ asset('img/favicon.ico') }}">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
        <title> Bonsaï la part du colibri </title>
        <meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport'/>

        <!--     Fonts and icons     -->
        <link rel="stylesheet" type="text/css"
              href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons"/>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
        {% block stylesheets %}
            {{ encore_entry_link_tags('app_front') }}
        {% endblock %}
    </head>

    <body>
        {% include '_includes/_navbar.html.twig' %}

        <div class="content">
            <div class="container-fluid">
                {% for label, messages in app.flashes(['success', 'warning', 'danger']) %}
                    {% for message in messages %}
                        <div class="alert alert-{{ label }}" role="alert">
                            {{ message | raw }}
                        </div>
                    {% endfor %}
                {% endfor %}
                {% block body %}{% endblock %}
            </div>
        </div>

        {% block javascripts %}
            {{ encore_entry_script_tags('app_front') }}
        {% endblock %}
    </body>
</html>

templates/bootstrap_4_custom_layout.html.twig
{% use "bootstrap_4_layout.html.twig" %}

{% block checkbox_widget -%}
    {%- set parent_label_class = parent_label_class|default(label_attr.class|default('')) -%}

    {%- if 'checkbox-custom' in parent_label_class -%}
        {%- set attr = attr|merge({class: (attr.class|default('') ~ ' custom-control-input')|trim}) -%}
        <div class="custom-control custom-checkbox{{ 'checkbox-inline' in parent_label_class ? ' custom-control-inline' }}">
            {{- form_label(form, null, { widget: parent() }) -}}
        </div>
    {%- elseif 'switch-custom' in parent_label_class -%}
        {%- set attr = attr|merge({class: (attr.class|default('') ~ ' custom-control-input')|trim}) -%}
        <div class="custom-control custom-switch{{ 'switch-inline' in parent_label_class ? ' custom-control-inline' }}">
            {{- form_label(form, null, { widget: parent() }) -}}
        </div>
    {%- else -%}
        {%- set attr = attr|merge({class: (attr.class|default('') ~ ' form-check-input')|trim}) -%}
        <div class="form-check{{ 'checkbox-inline' in parent_label_class ? ' form-check-inline' }}">
            <label class="form-check-label">
                <input type="checkbox" {{ block('widget_attributes') }}{% if value is defined %} value="{{ value }}"{% endif %}{% if checked %} checked="checked"{% endif %} />

                {{- label|raw -}}

                <span class="form-check-sign">
                <span class="check"></span>
            </span>
            </label>
        </div>
    {%- endif -%}
{%- endblock checkbox_widget %}

{% block file_widget -%}
{#    <{{ element|default('div') }} class="custom-file">#}
    <div class="form-group form-file-upload form-file-multiple">
    {%- set type = type|default('file') -%}
    {{- block('form_widget_simple') -}}
    <div class="input-group">
        <input type="text" class="form-control inputFileVisible image" placeholder="Un seul fichier">
        <span class="input-group-btn">
            <button type="button" class="btn btn-fab btn-round btn-primary">
                <i class="material-icons">attach_file</i>
            </button>
        </span>
    </div>
    {%- set label_attr = label_attr|merge({ class: (label_attr.class|default('') ~ ' custom-file-label')|trim }) -%}
    {%- set input_lang = 'en' -%}
    {% if app is defined and app.request is defined %}{%- set input_lang = app.request.locale -%}{%- endif -%}
{#    <label for="{{ form.vars.id }}" lang="{{ input_lang }}" {% with { attr: label_attr } %}{{ block('attributes') }}{% endwith %}>#}
{#        {%- if attr.placeholder is defined and attr.placeholder is not none -%}#}
{#            {{- translation_domain is same as(false) ? attr.placeholder : attr.placeholder|trans({}, translation_domain) -}}#}
{#        {%- endif -%}#}
{#    </label>#}
{#    </{{ element|default('div') }}>#}
    </div>
{% endblock %}

{% block form_errors -%}
    {%- if errors|length > 0 -%}
        {%- for error in errors -%}
            <span class="d-block mb-2">
                   <span class="form-error-message text-danger">{{ error.message }}</span>
                </span>
        {%- endfor -%}
    {%- endif %}
{%- endblock form_errors %}

templates/bootstrap_paginator.html.twig
{% if pageCount > 1 %}
    <ul class="pagination justify-content-center">
        {% if previous is defined %}
            <li class="page-item">
                <a rel="prev" href="{{ path(route, query|merge({(pageParameterName): previous})) }}" class="page-link">&laquo;&nbsp; Précédent</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span class="page-link">&laquo;&nbsp; Précédent</span>
            </li>
        {% endif %}

        {% if startPage > 1 %}
            <li class="page-item">
                <a href="{{ path(route, query|merge({(pageParameterName): 1})) }}" class="page-link">1</a>
            </li>
            {% if startPage == 3 %}
                <li class="page-item">
                    <a href="{{ path(route, query|merge({(pageParameterName): 2})) }}" class="page-link">2</a>
                </li>
            {% elseif startPage != 2 %}
                <li class="page-item disabled">
                    <span class="page-link">&hellip;</span>
                </li>
            {% endif %}
        {% endif %}

        {% for page in pagesInRange %}
            {% if page != current %}
                <li class="page-item">
                    <a href="{{ path(route, query|merge({(pageParameterName): page})) }}" class="page-link">{{ page }}</a>
                </li>
            {% else %}
                <li class="active page-item">
                    <span class="page-link">{{ page }}</span>
                </li>
            {% endif %}

        {% endfor %}

        {% if pageCount > endPage %}
            {% if pageCount > (endPage + 1) %}
                {% if pageCount > (endPage + 2) %}
                    <li class="page-item disabled">
                        <span class="page-link">&hellip;</span>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a href="{{ path(route, query|merge({(pageParameterName): (pageCount - 1)})) }}" class="page-link">{{ pageCount -1 }}</a>
                    </li>
                {% endif %}
            {% endif %}
            <li>
                <a href="{{ path(route, query|merge({(pageParameterName): pageCount})) }}" class="page-link">{{ pageCount }}</a>
            </li>
        {% endif %}

        {% if next is defined %}
            <li class="page-item">
                <a rel="next" class="page-link" href="{{ path(route, query|merge({(pageParameterName): next})) }}">Suivant&nbsp;&raquo;</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span class="page-link"> Suivant&nbsp;&raquo;</span>
            </li>
        {% endif %}
    </ul>
{% endif %}