src/Entity/Tree.php
<?php

namespace App\Entity;

use App\Manager\TreeStatusManager;
use App\Repository\TreeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
 * @ORM\Entity(repositoryClass=TreeRepository::class)
 * @ORM\EntityListeners({"App\EventListener\TreeListener"})
 */
class Tree extends QrCode
{
    use TimestampableEntity;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $qrCode;

    /**
     * @ORM\ManyToOne(targetEntity=Species::class)
     * @ORM\JoinColumn(onDelete="SET NULL")
     */
    private $species;

    /**
     * @ORM\ManyToOne(targetEntity=ColumnRow::class)
     * @ORM\JoinColumn(onDelete="SET NULL")
     */
    private $position;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $ageRecovery;

    /**
     * @ORM\Column(type="boolean")
     */
    private $output = false;

    /**
     * @ORM\ManyToOne(targetEntity=OutputType::class)
     */
    private $outputType;

    /**
     * @ORM\ManyToMany(targetEntity=Style::class)
     * @ORM\JoinColumn(onDelete="SET NULL")
     */
    private $potentialStyles;

    /**
     * @ORM\ManyToMany(targetEntity=Category::class)
     */
    private $categories;

    /**
     * @ORM\OneToMany(targetEntity=TreeGrowth::class, mappedBy="tree", orphanRemoval=true)
     */
    private $treeGrowths;

    /**
     * @ORM\OneToMany(targetEntity=TreePicture::class, mappedBy="tree", orphanRemoval=true, cascade={"persist", "remove"})
     */
    private $treePictures;

    /**
     * @ORM\OneToMany(targetEntity=HistoryTree::class, mappedBy="tree", orphanRemoval=true, cascade={"persist", "remove"})
     * @ORM\OrderBy({"date" = "DESC", "id" = "DESC"})
     */
    private $historyTrees;

    /**
     * @ORM\ManyToOne(targetEntity=Lot::class, inversedBy="trees")
     */
    private $lot;

    /**
     * @ORM\ManyToOne(targetEntity=Nursery::class, inversedBy="trees")
     * @ORM\JoinColumn(nullable=false)
     */
    private $nursery;

    /**
     * @ORM\OneToMany(targetEntity=TreeWork::class, mappedBy="tree", orphanRemoval=true, cascade={"persist", "remove"})
     */
    private $works;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $height;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $nebariDiameter;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $trunkDiameter;

    /**
     * @ORM\Column(type="integer")
     */
    private $status = TreeStatusManager::NOT_ADOPTABLE;

    /**
     * @ORM\OneToOne(targetEntity=Adoption::class, mappedBy="tree", cascade={"persist", "remove"})
     */
    private $adoption;

    /**
     * @ORM\OneToOne(targetEntity=DeadTree::class, mappedBy="tree", cascade={"persist", "remove"})
     */
    private $deadTree;

    /**
     * @ORM\ManyToOne(targetEntity=PotType::class)
     */
    private $potType;

    /**
     * @ORM\ManyToOne(targetEntity=Greenhouse::class, inversedBy="trees")
     */
    private $greenhouse;

    /**
     * @ORM\ManyToOne(targetEntity=CultureTable::class)
     */
    private $cultureTable;

    /**
     * @ORM\ManyToOne(targetEntity=Segment::class)
     */
    private $segment;

    /**
     * @ORM\ManyToOne(targetEntity=TableColumn::class)
     */
    private $tableColumn;

    /**
     * @ORM\ManyToOne(targetEntity=ColumnRow::class)
     */
    private $columnRow;

    /**
     * @ORM\OneToMany(targetEntity=Observation::class, mappedBy="tree", orphanRemoval=true)
     */
    private $observations;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $workingYear;

    public function __construct()
    {
        $this->treeGrowths = new ArrayCollection();
        $this->treePictures = new ArrayCollection();
        $this->historyTrees = new ArrayCollection();
        $this->works = new ArrayCollection();
        $this->potentialStyles = new ArrayCollection();
        $this->categories = new ArrayCollection();
        $this->observations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQrCode(): ?string
    {
        return $this->qrCode;
    }

    public function setQrCode(string $qrCode): self
    {
        $this->qrCode = $qrCode;

        return $this;
    }

    public function getSpecies(): ?Species
    {
        return $this->species;
    }

    public function setSpecies(?Species $species): self
    {
        $this->species = $species;

        return $this;
    }

    public function getAge(): ?int
    {
        if ($this->getAgeRecovery())
        {
            if ($this->getLot() && ($dateRecovery = $this->getLot()->getEntryDate()))
            {
                return $this->getAgeRecovery() + date_diff($dateRecovery, new \DateTime())->y;
            }

            return $this->getAgeRecovery();
        }

        if (($lot = $this->getLot()) && $lot->getAgeRecovery() && ($dateRecovery = $lot->getEntryDate()))
        {
            return $this->getLot()->getAgeRecovery() + date_diff($dateRecovery, new \DateTime())->y;
        }

        return null;
    }

    public function getAgeRecovery(): ?int
    {
        return $this->ageRecovery;
    }

    public function setAgeRecovery(?int $ageRecovery): self
    {
        $this->ageRecovery = $ageRecovery;

        return $this;
    }

    public function getOutput(): ?bool
    {
        return $this->output;
    }

    public function setOutput(bool $output): self
    {
        $this->output = $output;

        return $this;
    }

    public function getOutputType(): ?OutputType
    {
        return $this->outputType;
    }

    public function setOutputType(?OutputType $outputType): self
    {
        $this->outputType = $outputType;

        return $this;
    }

    /**
     * @return Collection|TreeGrowth[]
     */
    public function getTreeGrowths(): Collection
    {
        return $this->treeGrowths;
    }

    public function addTreeGrowth(TreeGrowth $treeGrowth): self
    {
        if (!$this->treeGrowths->contains($treeGrowth)) {
            $this->treeGrowths[] = $treeGrowth;
            $treeGrowth->setTree($this);
        }

        return $this;
    }

    public function removeTreeGrowth(TreeGrowth $treeGrowth): self
    {
        if ($this->treeGrowths->removeElement($treeGrowth)) {
            // set the owning side to null (unless already changed)
            if ($treeGrowth->getTree() === $this) {
                $treeGrowth->setTree(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|TreePicture[]
     */
    public function getTreePictures(): Collection
    {
        return $this->treePictures;
    }

    public function addTreePicture(TreePicture $treePicture): self
    {
        if (!$this->treePictures->contains($treePicture)) {
            $this->treePictures[] = $treePicture;
            $treePicture->setTree($this);
        }

        return $this;
    }

    public function removeTreePicture(TreePicture $treePicture): self
    {
        if ($this->treePictures->removeElement($treePicture)) {
            // set the owning side to null (unless already changed)
            if ($treePicture->getTree() === $this) {
                $treePicture->setTree(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|HistoryTree[]
     */
    public function getHistoryTrees(): Collection
    {
        return $this->historyTrees;
    }

    public function addHistoryTree(HistoryTree $historyTree): self
    {
        if (!$this->historyTrees->contains($historyTree)) {
            $this->historyTrees[] = $historyTree;
            $historyTree->setTree($this);
        }

        return $this;
    }

    public function removeHistoryTree(HistoryTree $historyTree): self
    {
        if ($this->historyTrees->removeElement($historyTree)) {
            // set the owning side to null (unless already changed)
            if ($historyTree->getTree() === $this) {
                $historyTree->setTree(null);
            }
        }

        return $this;
    }

    public function getLot(): ?Lot
    {
        return $this->lot;
    }

    public function setLot(?Lot $lot): self
    {
        $this->lot = $lot;

        return $this;
    }

    public function getNursery(): ?Nursery
    {
        return $this->nursery;
    }

    public function setNursery(?Nursery $nursery): self
    {
        $this->nursery = $nursery;

        return $this;
    }

    /**
     * @return Collection|TreeWork[]
     */
    public function getWorks(): Collection
    {
        return $this->works;
    }

    public function addWork(TreeWork $work): self
    {
        if (!$this->works->contains($work)) {
            $this->works[] = $work;
            $work->setTree($this);
        }

        return $this;
    }

    public function removeWork(TreeWork $work): self
    {
        if ($this->works->removeElement($work)) {
            // set the owning side to null (unless already changed)
            if ($work->getTree() === $this) {
                $work->setTree(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Style[]
     */
    public function getPotentialStyles(): Collection
    {
        return $this->potentialStyles;
    }

    public function addPotentialStyle(Style $potentialStyle): self
    {
        if (!$this->potentialStyles->contains($potentialStyle)) {
            $this->potentialStyles[] = $potentialStyle;
        }

        return $this;
    }

    public function removePotentialStyle(Style $potentialStyle): self
    {
        $this->potentialStyles->removeElement($potentialStyle);

        return $this;
    }

src/Controller/TreeController.php
<?php

namespace App\Controller;

use App\Entity\Adoption;
use App\Entity\Owner;
use App\Entity\Tree;
use App\Manager\AdoptionManager;
use App\Manager\TreeManager;
use App\Manager\TreeStatusManager;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/arbres", name="app_")
 */
class TreeController extends GeneralController
{
    /**
     * @Route("", name="tree_list")
     */
    public function listAction(Request $request, TreeManager $treeManager, PaginatorInterface $paginator): Response
    {
        $trees = $treeManager->getAdoptableTrees();

        $paginatorTrees = $paginator->paginate(
            $trees,
            $request->query->getInt('page', 1),
            16 // Nombre de résultats par page
        );

        return $this->render('tree/list.html.twig', [
            'trees' => $paginatorTrees,
            'numberTrees' => count($trees)
        ]);
    }

    /**
     * @Route("/detail/{id}", name="tree_detail")
     */
    public function detailAction(Request $request, Tree $tree): Response
    {
        $show = $request->get('show');

        if (!$show && $this->getUser()) {
            return $this->redirectToRoute('app_admin_tree_edit', [
                'id' => $tree->getId()
            ]);
        }

        return $this->render('tree/detail.html.twig', [
            'tree' => $tree
        ]);
    }

    /**
     * @Route("/{id}/adoption", name="tree_adoption")
     */
    public function adopt(Tree $tree, AdoptionManager $adoptionManager): Response
    {
        if (!$this->getUser())
        {
            return $this->redirectToRoute('app_login');
        }

        /** @var Owner $owner */
        $owner = $this->getUser();

        $adoption = new Adoption();
        $adoption->setTree($tree);
        $adoption->setOwner($owner);
        $tree->setStatus(TreeStatusManager::ADOPT);

        $adoptionManager->save($adoption);

        return $this->redirectToRoute('app_tree_list');
    }
}

templates/tree/detail.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="row">
        <div class="col-md-12 text-center">
            <img src="{{ asset('img/logo.jpg') }}" height="200" alt="">
        </div>
        <div class="col-md-8 offset-2">
            <div class="card">
                <div class="card-header card-header-info">
                    <h4 class="card-title"> Détail de l'arbre {{ tree }}</h4>
                </div>
                <div class="card-body p-3">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="col-md-12 mb-5">
                                <div class="card card-nav-tabs">
                                    <div class="card-header card-header-success">
                                        Informations générales
                                    </div>
                                    <div class="cart-body p-3">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <p>
                                                    <b> Âge: </b> {{ tree.age ? tree.age ~ ' ans' : '-' }} <br/>
                                                    <b> Espèce: </b> {{ tree.species ? tree.species : '-' }} <br/>
                                                    <b> Catégorie: </b> {{ not tree.categories.isEmpty ? tree.categoriesStr : '-' }} <br/>
                                                    <b> Styles potentiels: </b> {{ not tree.potentialStyles.isEmpty ? tree.potentialStylesStr : '-' }} <br/>
                                                    {% if not tree.adoption %}
                                                        <b> Serre: </b> {{ tree.greenhouse }} {{ tree.greenhouse ? '(' ~ tree.greenhouse.location ~ ')' : '' }} <br/>
                                                    {% endif %}
                                                    <b> Année de travail: </b> {{ tree.workingYear == 1 ? "-5 ans" : tree.workingYear == 2 ?  tree.workingYear == 3 ? '5-10 ans' : '-' }} <br/>
                                                </p>
                                            </div>
                                            <div class="col-md-6">
                                                <p>
                                                    {% if tree.species %}
                                                        <b> Type de feuille: </b> {{ tree.species.leafType ? tree.species.leafType : '-' }} <br/>
                                                        <b> Exposition: </b> {{ tree.species.recommendedExposure ? tree.species.recommendedExposure | labelExposure : '-' }} <br/>
                                                        <b> Besoin en engrais: </b> {{ tree.species.fertilizerNeed ? tree.species.fertilizerNeed | labelFertilizer : '-' }} <br/>
                                                        <b> Statut UICN: </b> {{ tree.species.statusUicn ? tree.species.statusUicn : '-' }} <br/>
                                                    {% endif %}
                                                </p>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>

                            {% if tree.lot %}
                                <div class="col-md-12 mb-5">
                                    <div class="card card-nav-tabs">
                                        <div class="card-header card-header-success">
                                            Prélèvement
                                        </div>
                                        <div class="cart-body p-3">
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <p>
                                                        <b> Date: </b> {{ tree.lot.entryDate ? tree.lot.entryDate | date('d/m/Y') : '-' }} <br/>
                                                        <b> Lieu: </b> {{ tree.lot.place ? tree.lot.place : '-' }} <br/>
                                                        <b> Ville: </b> {{ tree.lot.city ? tree.lot.city : '-' }} <br/>
                                                        <b> Code postal: </b> {{ tree.lot.postalCode ? tree.lot.postalCode : '-' }} <br/>
                                                    </p>
                                                </div>

                                                <div class="col-md-6">
                                                    <p>
                                                        <b> Cause: </b> <br/>{{ tree.lot.recoveryCause ? tree.lot.recoveryCause | raw | nl2br : '-' }} <br/>
                                                    </p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endif %}

                            <div class="col-md-12">
                                <div class="card card-nav-tabs">
                                    <div class="card-header card-header-success">
                                        Travaux
                                    </div>
                                    <div class="cart-body p-3">
                                        {% if tree.works.empty %}
                                            Aucun travaux effectué sur cet arbre.
                                        {% else %}
                                            <table class="table">
                                                <thead>
                                                    <tr>
                                                        <th> Date </th>
                                                        <th> Travaux </th>
                                                        <th> Commentaire </th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    {% for work in tree.works %}
                                                        <tr>
                                                            <td> {{ work.date | date('d/m/Y') }} </td>
                                                            <td> {{ work.work }} </td>
                                                            <td> {{ work.comment }} </td>
                                                        </tr>
                                                    {% endfor %}
                                                </tbody>
                                            </table>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-6">
                            {% include 'tree/includes/_history.html.twig' %}

                            <div class="row">
                                <div class="col-md-12">
                                    {% for picture in tree.treePictures %}
                                        <img src="{{ asset(picture.path) }}" alt="" height="150px">
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-8 offset-2 text-center">
        <a href="{{ path('app_admin_tree_edit', { id: tree.id }) }}"> <i class="material-icons">lock</i> Administrer
        </a>
    </div>
    </div>

{% endblock %}

templates/tree/list.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <p class="h3"> Il y a <span class="h2 text-primary"> {{ numberTrees }} </span> arbres </p>

    <div class="row">
        {% for tree in trees %}
            <div class="col-md-4 col-lg-3 text-center block-tree">
                <div class="col-md-12">
                    <a href="{{ path('app_tree_detail', { id: tree.id }) }}">
                        <img src="{{ asset(tree | mainPicture ) }}" class="img-responsive" height="300" alt="bonsai">
                    </a>
                    <a href="{{ path('app_tree_adoption', { id: tree.id }) }}"
                       class="btn btn-primary btn-block {% if tree.adoption %} disabled {% endif %}">
                        Parrainer
                    </a>
                </div>

                <div class="col-md-12 mt-2">
                    <p class="h4">
                        <a href="{{ path('app_tree_detail', { id: tree.id }) }}">
                            {{ tree ~ ' ' ~ tree.species }}
                        </a>
                    </p>
                    <p>
                        {% for category in tree.categories %}
                            <span class="badge badge-dark"> {{ category }} </span>
                        {% endfor %}
                        {% for potentialStyle in tree.potentialStyles %}
                            <span class="badge badge-secondary"> {{ potentialStyle }} </span>
                        {% endfor %}
                    </p>
                </div>
                
            </div>
        {% endfor %}
    </div>

    {{ knp_pagination_render(trees) }}

{% endblock %}